#!/usr/bin/env python3

import argparse
import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import Circle


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Plot the trajectory generated by ccbf_simulation."
    )
    parser.add_argument(
        "csv_path",
        nargs="?",
        default="ccbf_simulation.csv",
        help="Simulation CSV generated by ccbf_simulation.",
    )
    parser.add_argument(
        "--save",
        metavar="PNG_PATH",
        help="Save the figure to this path.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open an interactive Matplotlib window.",
    )
    return parser.parse_args()


def load_simulation(csv_path):
    with csv_path.open(newline="") as stream:
        reader = csv.DictReader(stream)
        rows = list(reader)

    if not rows:
        raise ValueError(f"simulation CSV is empty: {csv_path}")

    required = {
        "time",
        "x",
        "y",
        "nominal_vx",
        "nominal_vy",
        "safe_vx",
        "safe_vy",
        "min_barrier",
        "goal_x",
        "goal_y",
    }
    missing = required.difference(rows[0])
    if missing:
        raise ValueError(f"missing CSV columns: {', '.join(sorted(missing))}")

    data = {
        name: [float(row[name]) for row in rows]
        for name in required
        if name not in {"goal_x", "goal_y"}
    }
    goal = (float(rows[0]["goal_x"]), float(rows[0]["goal_y"]))

    obstacles = []
    index = 1
    while f"obstacle_{index}_x" in rows[0]:
        obstacles.append(
            (
                float(rows[0][f"obstacle_{index}_x"]),
                float(rows[0][f"obstacle_{index}_y"]),
                float(rows[0][f"obstacle_{index}_radius"]),
            )
        )
        index += 1

    if not obstacles:
        raise ValueError("the CSV does not contain any obstacles")

    return data, goal, obstacles


def plot_simulation(data, goal, obstacles):
    figure = plt.figure(figsize=(13, 8))
    grid = figure.add_gridspec(2, 2, width_ratios=(1.6, 1.0))
    trajectory_axis = figure.add_subplot(grid[:, 0])
    velocity_axis = figure.add_subplot(grid[0, 1])
    barrier_axis = figure.add_subplot(grid[1, 1])

    trajectory_axis.plot(
        [data["x"][0], goal[0]],
        [data["y"][0], goal[1]],
        "--",
        color="0.65",
        linewidth=1.5,
        label="nominal pathline",
    )
    trajectory_axis.plot(
        data["x"],
        data["y"],
        color="tab:blue",
        linewidth=2.2,
        label="CBF-filtered trajectory",
    )
    trajectory_axis.scatter(
        data["x"][0],
        data["y"][0],
        marker="o",
        s=70,
        color="tab:green",
        zorder=5,
        label="start",
    )
    trajectory_axis.scatter(
        goal[0],
        goal[1],
        marker="*",
        s=180,
        color="gold",
        edgecolor="black",
        linewidth=0.7,
        zorder=5,
        label="goal",
    )

    for index, (center_x, center_y, radius) in enumerate(obstacles):
        obstacle = Circle(
            (center_x, center_y),
            radius,
            facecolor="tab:red",
            edgecolor="darkred",
            alpha=0.28,
            linewidth=1.5,
            label="CBF obstacle boundary" if index == 0 else None,
        )
        trajectory_axis.add_patch(obstacle)
        trajectory_axis.scatter(
            center_x,
            center_y,
            marker="x",
            color="darkred",
            s=35,
            zorder=4,
        )
        trajectory_axis.text(
            center_x,
            center_y + radius + 0.08,
            str(index + 1),
            horizontalalignment="center",
            color="darkred",
        )

    nominal_speed = [
        math.hypot(vx, vy)
        for vx, vy in zip(data["nominal_vx"], data["nominal_vy"])
    ]
    safe_speed = [
        math.hypot(vx, vy)
        for vx, vy in zip(data["safe_vx"], data["safe_vy"])
    ]
    velocity_axis.plot(
        data["time"],
        nominal_speed,
        "--",
        color="0.45",
        label="nominal speed",
    )
    velocity_axis.plot(
        data["time"],
        safe_speed,
        color="tab:blue",
        label="safe speed",
    )
    velocity_axis.set_ylabel("linear speed [m/s]")
    velocity_axis.set_title("Nominal and filtered commands")
    velocity_axis.grid(True, alpha=0.3)
    velocity_axis.legend()

    barrier_axis.plot(
        data["time"],
        data["min_barrier"],
        color="tab:purple",
        label="minimum obstacle h",
    )
    barrier_axis.axhline(
        0.0,
        color="tab:red",
        linestyle="--",
        linewidth=1.2,
        label="safety boundary",
    )
    barrier_axis.set_xlabel("time [s]")
    barrier_axis.set_ylabel("barrier value h")
    barrier_axis.set_title("Closest CBF constraint")
    barrier_axis.grid(True, alpha=0.3)
    barrier_axis.legend()

    trajectory_axis.set_title("Five-obstacle CCBF pathline simulation")
    trajectory_axis.set_xlabel("x [m]")
    trajectory_axis.set_ylabel("y [m]")
    trajectory_axis.set_aspect("equal", adjustable="box")
    trajectory_axis.grid(True, alpha=0.3)
    trajectory_axis.legend(loc="upper left")
    trajectory_axis.margins(0.08)

    figure.tight_layout()
    return figure


def main():
    arguments = parse_arguments()
    csv_path = Path(arguments.csv_path)
    data, goal, obstacles = load_simulation(csv_path)
    figure = plot_simulation(data, goal, obstacles)

    if arguments.save:
        output_path = Path(arguments.save)
        figure.savefig(output_path, dpi=160, bbox_inches="tight")
        print(f"Saved plot: {output_path}")

    if not arguments.no_show:
        plt.show()


if __name__ == "__main__":
    main()
